# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "quiz-app"
handle = "quiz-app-88"
application_url = "https://stallion-inviting-gnu.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = false

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [
  "https://stallion-inviting-gnu.ngrok-free.app/auth/callback",
  "https://stallion-inviting-gnu.ngrok-free.app/auth/shopify/callback",
  "https://stallion-inviting-gnu.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
